### ISSUE TITLE
Missing repository for viritin?

### ISSUE THREAD

**Issue by paulswithers** [mstahv/cassandra-spring-data-example#1]
I installed the project but got a pom.xml error regarding viritin. It looks like the pom.xml is missing the reference to the repository. Once I added in the following reference to the repository, it built successfully.

```
    <repositories>
        <repository>
            <id>vaadin-addons</id>
            <url>http://maven.vaadin.com/vaadin-addons</url>
        </repository>
    </repositories>
```

**Comment by mstahv** [comment]
Thanks!
